data:
  train_features_file: data/train_features.txt
  train_labels_file: data/train_labels.txt
  eval_features_file: data/eval_features.txt
  eval_labels_file: data/eval_labels.txt
  features_vocab_file: data/features_vocab.txt
  labels_vocab_file: data/labels_vocab.txt
  max_features_len: 30
  max_labels_len: 30
  out_dir: /tmp/model

params:
  optimizer: AdamOptimizer
  learning_rate: 1.0
  param_init: 0.1
  clip_gradients: 5.0
  regularization:
  average_loss_in_time: false
  decay_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 10000
  start_decay_steps: 100000
  min_learning_rate: 0.0001
  beam_width: 5
  replace_unknown_target: false

train:
  batch_size: 64
  save_checkpoints_steps: 5000
  keep_max_checkpoints: 5
  save_summary_steps: 100
  training_steps: 200000
  bucket_width: 5
  shuffle_buffer_size: 500000
  pefetch_buffer_size: 1
  average_last_checkpoints: 5

eval:
  batch_size: 32
  prefetch_buffer_size: 1
  eval_delay: 18000
  save_predictions: true
  external_evaluators: BLEU
  exporters: last

infer:
  batch_size: 32
  prefetch_buffer_size: 1
  n_best: 1