src: src
tgt: tgt
train_prefix: testdata/train
dev_prefix: testdata/dev
test_prefix: testdata/test
vocab_prefix: testdata/vocab
embed_prefix: testdata/embed
out_dir: /tmp/model
sos: <s>
eos: </s>
subword_option: bpe
check_special_token: false
num_units: 256
num_layers: 4
num_encoder_layers: 2
num_decoder_layers: 2
unit_type: lstm
dropout: 0.2
encoder_type: gnmt
residual: true
time_major: true
num_embeddings_partitions: 1
attention: normed_bahdanau
attention_architecture: gnmt_v2
output_attention: true
pass_hidden_state: true
optimizer: sgd
num_train_steps: 1000000
batch_size: 64
init_op: uniform
init_weight: 0.1
max_gradient_norm: 5.0
learning_rate: 1.0
warmup_steps: 0
warmup_scheme: t2t
decay_scheme:
colocate_gradients_with_ops: true
num_buckets: 5
max_train: 0
src_max_len: 50
tgt_max_len: 50
src_max_len_infer: 50
tgt_max_len_infer: 50
infer_batch_size: 32
beam_width: 10
length_penalty_weight: 1.0
num_translations_per_input: 1
forget_bias: 1.0
num_gpus: 1
epoch_step: 0
steps_per_stats: 100
steps_per_external_eval:
share_vocab: false
metrics: blue
log_device_placement: false
random_seed:
override_loaded_params: false
num_keep_ckpts: 5
avg_ckpts: true
num_intra_threads: 0
num_inter_threads: 0
sampling_temperature: 0.0

